SystemOrganization addCategory: #TaskIT2!
SystemOrganization addCategory: 'TaskIT2-Builder'!
SystemOrganization addCategory: 'TaskIT2-Collections'!
SystemOrganization addCategory: 'TaskIT2-Job'!
SystemOrganization addCategory: 'TaskIT2-Job-Futures'!
SystemOrganization addCategory: 'TaskIT2-Kernel'!
SystemOrganization addCategory: 'TaskIT2-Kernel-Announcements'!
SystemOrganization addCategory: 'TaskIT2-Runner'!
